### ISSUE TITLE
New nice boost link

### ISSUE THREAD

**Issue by jakubsta** [Userfeeds/Apps#103]
Actions:
- [x] Ask @patrykadas about final version

![innewersje](https://user-images.githubusercontent.com/7150839/33134510-3502ea02-cfa0-11e7-8de3-e7468428023c.png)

**Comment by patrykadas** [comment]
![boost](https://user-images.githubusercontent.com/6234032/33173549-dd7d571c-d054-11e7-8dae-6ff06cf5e964.png)

The only thing I'm unsure about is how to solve the input issue, rest seems to be clear.

We want to display:
1. Current probability (not changable for obvious reasons)
2. Desired probability (slider and / or input)
3. Change in probability (slider)
4. Your balance in suitable currency
5. Amount to pay (input & slider)
6. Link's position (whitelisted / in slot)

**Comment by jakubsta** [comment]
@patrykadas I've found a solution for the input, let's use `<marquee>`. :joy:
