### ISSUE TITLE
Restyle: Create new link to match design

### ISSUE THREAD

**Issue by michalwarda** [Userfeeds/Apps#116]
https://projects.invisionapp.com/d/main#/console/12058812/254052334/preview

**Comment by patrykadas** [comment]
![createad_1 2x](https://user-images.githubusercontent.com/6234032/34744643-34bafe40-f58e-11e7-8b36-4f15c2831f7d.png)

I was thinking if perhaps we can simplify it, as the left side perhaps could be omitted. I've also tried to combine "Initial fee" with CTA.

**Comment by patrykadas** [comment]
@jakubsta 
![createlink](https://user-images.githubusercontent.com/6234032/35799510-3b9086ee-0a66-11e8-83bd-d55af1a93b3b.png)
https://projects.invisionapp.com/share/HREPJE43P#/screens/266610597

**Comment by gkapkowski** [comment]
What about validation messages provided by client?

**Comment by patrykadas** [comment]
@gkapkowski 
<img width="623" alt="screen shot 2018-02-06 at 13 01 40" src="https://user-images.githubusercontent.com/6234032/35858776-fc76f3e8-0b3d-11e8-8f51-eada1f3f8269.png">
Also updated Invision @jakubsta

**Comment by gkapkowski** [comment]
Cool, so we have per-field errors and general error, good. 👍

**Comment by jakubsta** [comment]
Resolved #188
