### ISSUE TITLE
Countdown bar more visible

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#130]
![blocks](https://user-images.githubusercontent.com/6234032/34741305-7c6b05e8-f582-11e7-9280-1be1d5998454.png)
![biddingover 2x](https://user-images.githubusercontent.com/6234032/34741307-7d5ad280-f582-11e7-9bea-3ead069b61f6.png)

 I'm not sure if the bar now is not too prominent, feedback appreciated.

**Comment by gkapkowski** [comment]
The bar is too big :) half of the height would be good IMO.

**Comment by patrykadas** [comment]
Let's continue in #134
