### ISSUE TITLE
Boost permissions and transition 

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#131]
![boosts 2x](https://user-images.githubusercontent.com/6234032/34741381-c5ec4f2e-f582-11e7-9a1f-0957fcd1244d.png)

Boosts are different for the links in the slots, and for the ones approved. Animation to add more context and show that we're accepting pre-defined action.

https://youtu.be/z9TYHwqRhek

**Comment by patrykadas** [comment]
We've discussed it internally with @michalwarda and @jakubsta 
![boost](https://user-images.githubusercontent.com/6234032/35501059-04998ad8-04d9-11e8-9cc9-089289a8c853.png)

Fixes:
1. I'd by default add +1%, so it's not disabled in the beginning.
2. Can we perhaps round up the value based on the token value? For instance: ETH could be rounded up to 8th, 9th place after the comma, whereas BEN to 2nd / 3rd; of course user can type in value manually as well. 
3. Once user progresses and yet there's no accepteded funds in his account, we should ask him for permission. 
4. If the checkbox's selected, we show the total balance of tokens in address.
5. If the checkbox's not selected, we show only the balance for this transaction.
6. After clicking 'Confirm' we launch Metamask for the first time to validate choice explained above.
7. After this transaction's went through, we launch Metamask again. I think that it should happen simultaneously, without triggering it by the user, however I'm not sure and I could use feedback here.

**Comment by patrykadas** [comment]
By @jakubsta suggestion, adding one more screen once first Metamask is launched:
![boost_rework](https://user-images.githubusercontent.com/6234032/35504393-3b8f45b4-04e3-11e8-9181-3c61a68c3d34.png)

**Comment by patrykadas** [comment]
![boost](https://user-images.githubusercontent.com/6234032/35567516-a292eb84-05c5-11e8-8082-7ce947fd7cbe.png)

**Comment by gkapkowski** [comment]
This is great, I can see clearly every step. Good job!

**Comment by patrykadas** [comment]
![boost](https://user-images.githubusercontent.com/6234032/35581457-19d3a3fc-05ec-11e8-9525-126b6ab7971f.png)

Forgot about 'whitelisted' 

Invision:
https://projects.invisionapp.com/d/main#/console/12725721/276024410/preview

**Comment by jakubsta** [comment]
Closing it because it's done besides final touches like hovers and etc.
