### ISSUE TITLE
Video widget's CSS improvements

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#132]
https://framer.cloud/OYhUq
(Grey box triggers animation transition)
https://youtu.be/XzDoWpC_QcE

Would it be difficult to define some :before element that could provide something similiar to drawing lots?

- [x] progressbar
- [ ] transition

**Comment by gkapkowski** [comment]
We decided to go without percentage for Bentyn as it is confusing for users at this stage.

We need to prepare easily customizable bottom/top widgets. right now we require deploy to switch those settings.

**Comment by patrykadas** [comment]
@jakubsta this is what I meant with the progress bar loader. Also, would be awesome to add this transition animation, however it's super low priority:
https://codepen.io/soulwire/pen/mErPAK?q=text&limit=all&type=type-pens
