### ISSUE TITLE
Link status

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#133]
Would it be possible to provide preview of the widget in a frame, as intended afterwards?

![linkstatus2 1x](https://user-images.githubusercontent.com/6234032/34742404-60edbc76-f586-11e7-9580-6d0dec240d30.png)

As @gkapkowski suggested I also tried to indicate loading process on particular step:
https://codepen.io/patrykadas/pen/KZQxeP

**Comment by patrykadas** [comment]
If the network is slow, we should alert the user. 
![warning](https://user-images.githubusercontent.com/6234032/34743681-e8d7056c-f58a-11e7-81c6-b74867ef6b9b.png)

**Comment by gkapkowski** [comment]
This is super awesome design. I really like it.

**Comment by patrykadas** [comment]
Continue in #169
