### ISSUE TITLE
Version 0.0.141 broke https://linkexchange.io/widgets-dev but SoTD works

### ISSUE THREAD

**Issue by gkapkowski** [Userfeeds/Apps#153]
I have no idea why but when I refresh https://linkexchange.io/widgets-dev there are no widgets but SoTD works fine and looks like it has required changes

**Comment by jakubsta** [comment]
![image](https://user-images.githubusercontent.com/7150839/34931332-25c82c6e-f9c6-11e7-8c18-1ad871d70dbf.png)

**Comment by gkapkowski** [comment]
Yeah, I saw that, but before 0.0.141 release at least 3 widgets did render on https://linkexchange.io/widgets-dev. What could change so that now all of them do not render?
