### ISSUE TITLE
Define one formatter/prettier

### ISSUE THREAD

**Issue by jakubsta** [Userfeeds/Apps#157]
Define one formatter/prettier to prevent this kind of changes: 
https://github.com/Userfeeds/Apps/commit/a5b2c75e26ee046653f02a1de5c700d73514b66d#diff-501d8caeaa9a5dcb06712b4e3b8f4500R42

**Comment by michalwarda** [comment]
Pushed in https://github.com/Userfeeds/Apps/commit/36454ede6c6de8990d2eec38e84d18be03961ee6
