### ISSUE TITLE
LinkExchange widget: JS error `SyntaxError: Unexpected token '>'`

### ISSUE THREAD

**Issue by robyedlin** [Userfeeds/Apps#172]
SyntaxError: Unexpected token '>'
  at ? (/npm/@linkexchange/widgets@stable:48:0)

<img width="315" alt="screen shot 2018-02-07 at 4 57 06 pm" src="https://user-images.githubusercontent.com/10917203/35946058-fb0889b4-0c27-11e8-8f4f-649e122c310c.png">

**Comment by jakubsta** [comment]
@robyedlin Did it occurred again?

**Comment by robyedlin** [comment]
Haven't seen the error recently.

**Comment by jakubsta** [comment]
Ok, I'm closing it for now.
