### ISSUE TITLE
LinkExchange widget: UX issues

### ISSUE THREAD

**Issue by robyedlin** [Userfeeds/Apps#174]
1. Links rotate too fast, and seemingly at random time intervals
2. There's no way to manually get to next/prev links
3. There's no indication of how long a user has to click before the next one shows up.

**Comment by jakubsta** [comment]
> 1. Links rotate too fast, and seemingly at random time intervals

It can be resolved by increasing `timeslot` value from default 5s per link (https://userfeeds-platform.readthedocs-hosted.com/en/latest/ref/widgets.html)

**Comment by patrykadas** [comment]
@robyedlin 
I added this little bottom bar with arrows and progress indicator + CTA, it's not under the hover anymore; dunno if it's not too prominent though.

1. Circle progress bar around ETH:
https://framer.cloud/jJpEj

2. Horizontal progress bar:
https://framer.cloud/PKKVF

If the framer does not work for various reasons here's the video:
https://youtu.be/9-ke43Nr1wo

**Comment by robyedlin** [comment]
That's an interesting solution, nice. I think the circle progress bar is the best, personally. Horizontal bar is somewhat intrusive.

**Comment by patrykadas** [comment]
Squarish:
https://framer.cloud/jJpEj

Leaderboard:
https://framer.cloud/zuWaB

However I wouldn't reference them in widget script, just in CSS as our two first 'templates'
