### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#186]
Simple FAQ, as seen in #134 

Previews:
1. This one is triggered whenever user clicks an alert that's connected to Metamask.
http://highlight.is/FAQ-LE/index.html
2. Fixed one in header
http://highlight.is/FAQ-LE/faq-long.html

Source:
https://github.com/patrykadas/FAQ-LE

**Comment by jakubsta** [comment]
deployed to: https://linkexchange.io/faq/ and https://linkexchange.io/faq/mm.html
