### ISSUE TITLE
Show links with value 0 in Approved and not Slots

### ISSUE THREAD

**Issue by mg6maciej** [Userfeeds/Apps#187]
Links with value === '0' will not be shown in widget, so it's misleading to show them in in Slots.

(Remember to handle case where all links have value === '0')

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/1316369/36537393-483bf938-17d0-11e8-9b47-6fed8232eef8.png">

**Comment by gkapkowski** [comment]
:+1:
