### ISSUE TITLE
Whitelist should send shorter credits

### ISSUE THREAD

**Issue by gkapkowski** [Userfeeds/Apps#25]
https://rinkeby.etherscan.io/tx/0x7374dd63279ae4e3291235401b7dc86c502d90fefea71260c756f47c9adc1ced

currently is whole whitelsit url

Claim:
```
{"target":"userfeeds:claim:0xaf0bf52b186378f9e0e2b6d67fdfd75cb3b1930ab01044c70ab87d368008561b"},"credits":[{"type":"interface","value":"https://userfeeds.io/apps/links/#/whitelist/?context=rinkeby%3A0xfe5da6ae3f65e7d5ce29121a9f5872ffd83b45e6&algorithm=links&whitelist=rinkeby%3A0xfe5da6ae3f65e7d5ce29121a9f5872ffd83b45e6&publisherNote=Hello%20there!!!%20send%20me%20an%20email%20to%20g%40userfeeds.io"}]}
```

**Comment by mg6maciej** [comment]
How about sending `[{"type":"interface","value":"https://userfeeds.io/apps/links/#/whitelist/"}]`?

**Comment by gkapkowski** [comment]
Whitelist should not send any credits? Keeping whitelist url in db doesn't do anything good to anyone. noone will benefit by visiting whitelist alone.

Let's remove credits from whitelist.
