### ISSUE TITLE
CSS Fixes

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#83]
- [x] Border color vs background color in hover of 'New window'
<img width="438" alt="screen shot 2017-10-30 at 19 44 12" src="https://user-images.githubusercontent.com/6234032/32189912-645a60ce-bdac-11e7-88d2-29f776ab1f75.png">

- [x] Border radius, stroke width
<img width="228" alt="screen shot 2017-10-30 at 19 43 58" src="https://user-images.githubusercontent.com/6234032/32189907-5efec0fc-bdac-11e7-8ed5-78494911ee00.png">

- [x] Should be no underline
<img width="745" alt="screen shot 2017-10-30 at 19 45 02" src="https://user-images.githubusercontent.com/6234032/32190480-40a5510a-bdae-11e7-9486-0a5018329a0e.png">

- [x] This needs explanation and/or link to Github
<img width="736" alt="screen shot 2017-10-30 at 19 44 51" src="https://user-images.githubusercontent.com/6234032/32190503-52ea46ae-bdae-11e7-9ff8-9084c339ffd2.png">

- [x] Send button in boosting link, add padding
<img width="449" alt="screen shot 2017-10-30 at 19 43 44" src="https://user-images.githubusercontent.com/6234032/32190527-607a8090-bdae-11e7-80f1-399efed9c99d.png">

- [x] Opacity of the icon, not the icon's background
- [x] Widget's location link's look
<img width="449" alt="screen shot 2017-10-30 at 19 43 44" src="https://user-images.githubusercontent.com/6234032/32190565-7a3385b8-bdae-11e7-9af1-3da2effb79a4.png">

- [x] Confirmation's look, use our colors and center the content
<img width="267" alt="screen shot 2017-10-30 at 16 02 45" src="https://user-images.githubusercontent.com/6234032/32190599-90dc45e8-bdae-11e7-8841-3f7d0e6ef2ce.png">

**Comment by michalwarda** [comment]
I'll take it! @ja

**Comment by mg6maciej** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1316369/32201577-f0942a9a-bda5-11e7-9e4d-38678cab1737.png">
