### ISSUE TITLE
Metamask button

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#90]
<img width="719" alt="screen shot 2017-10-31 at 04 01 01" src="https://user-images.githubusercontent.com/6234032/32205552-278b46a6-bdf0-11e7-94a7-babca4079468.png">

Add 'Import from Metamask' next to input that needs your address.

- [x] Whitelist
- [x] Widget creation

**Comment by patrykadas** [comment]
![mm](https://user-images.githubusercontent.com/6234032/32236890-c1c5019e-be63-11e7-9c74-ab8b774ea611.png)

For now even this'd do.

**Comment by michalwarda** [comment]
This issue is almost done.
Add tooltip on hover with text: "Copy address from Metamask"
