### ISSUE TITLE
Link Status 'Add to bookmarks'

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/Apps#93]
- [x] Progress bar does not work
<img width="439" alt="screen shot 2017-10-31 at 12 19 14" src="https://user-images.githubusercontent.com/6234032/32221404-bdffbbf4-be35-11e7-83d8-967e6f21ead1.png">

- [x] Add to bookmarks hover 
<img width="210" alt="screen shot 2017-10-31 at 12 18 47" src="https://user-images.githubusercontent.com/6234032/32221440-d6c501c6-be35-11e7-99cd-d752cc858c27.png">

- [ ] Bookmarks action
<img width="502" alt="screen shot 2017-10-31 at 12 20 21" src="https://user-images.githubusercontent.com/6234032/32221459-e501c04e-be35-11e7-92e6-a8db4cee72cf.png">
Can't we just add it to bookmarks by clicking the button? What's the point of displaying the alert then? If not, what's the point of having the button instead of the info to CMD+D?

**Comment by jakubsta** [comment]
It's not a problem anymore because `Add to bookmarks` was removed.
